[versions]
agp = "8.13.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
lifecycleVMCompose="2.8.6"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
navCompose="2.8.7"
cameraX = "1.5.1"
zXing = "3.3.3"
compose = "1.9.3"
appcompat = "1.7.1"
material = "1.13.0"
materialIconsExtended = "1.7.5"
foundationLayout = "1.9.4"
firebaseBom="33.4.0"
firebaseUiAuth="7.2.0"
coilCompose="2.7.0"
googleServices="4.4.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-viewmodel-compose={group = "androidx.lifecycle",name="lifecycle-viewmodel-compose",version.ref="lifecycleVMCompose"}
androidx-navigation-compose = {group="androidx.navigation",name="navigation-compose",version.ref="navCompose"}
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
coil-compose={module="io.coil-kt:coil-compose", version.ref="coilCompose"}

# Firebase
firebase-bom = {module ="com.google.firebase:firebase-bom", version.ref="firebaseBom"}
firebase-firestore={module="com.google.firebase:firebase-firestore"}
firebase-storage={module="com.google.firebase:firebase-storage"}
firebase-ui-auth={module="com.firebaseui:firebase-ui-auth", version.ref="firebaseUiAuth"}

#Camera X
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX"}
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX"}
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraX"}

#Zxing
com-google-zxing-core = { module = "com.google.zxing:core", version.ref = "zXing" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }

androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-services ={id ="com.google.gms.google-services",version.ref="googleServices"}